sudo: false

cache:
  apt: true
  directories:
    - $HOME/.stack/
    - .stack-work/

matrix:
  include:
    - env: STACK_YAML=stack.yaml

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack install hlint weeder

script:
  - ./Shakefile.hs sanity
  - ./Shakefile.hs test
